/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : clockMan1.c
**     Project     : freertos_mpc5748g
**     Processor   : MPC5748G_324
**     Component   : clock_manager
**     Version     : Component SDK_MPC574x_02, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_MPC574x_02
**     Compiler    : GNU C Compiler
**     Date/Time   : 2018-03-28, 01:50, # CodeGen: 0
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016-2017 NXP
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file clockMan1.c
** @version 01.00
*/
/*!
**  @addtogroup clockMan1_module clockMan1 module documentation
**  @{
*/

/* clockMan1. */

#include "clockMan1.h"

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Required Rule 9.4, Duplicate initialization of object element.
 * It's the only way to initialize an array that is member of struct.
 *
 */
/* *************************************************************************
 * Configuration structure for peripheral clock configuration 0
 * ************************************************************************* */
/*! @brief peripheral clock configuration 0 */
mc_me_peripheral_clock_config_t peripheralClockMcMeConfig0[] = {
    {
        .clockName                      = ADC0_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = ADC1_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = BCTU0_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = CMP0_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = CMP1_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = CMP2_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = CRC0_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = DMA0_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = DMAMUX0_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = DSPI0_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = DSPI1_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = DSPI2_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = DSPI3_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = ENET0_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = FLEXCAN0_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = FLEXCAN1_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = FLEXCAN2_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = FLEXCAN3_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = FLEXCAN4_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = FLEXCAN5_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = FLEXCAN6_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = FLEXCAN7_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = FLEXRAY0_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = IIC0_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = IIC1_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = IIC2_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = IIC3_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = LIN0_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = LIN1_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = LIN2_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = LIN3_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = LIN4_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = LIN5_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = LIN6_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = LIN7_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = LIN8_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = LIN9_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = LIN10_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = LIN11_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = LIN12_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = LIN13_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = LIN14_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = LIN15_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = LIN16_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = LIN17_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = MEMU0_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = MEMU1_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = MLB0_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = PITRTI0_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = RTC0_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = SAI0_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = SAI1_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = SAI2_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = SDHC0_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = SPI0_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = SPI1_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = SPI2_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = SPI3_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = SPI4_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = SPI5_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = SIUL_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = USBOTG0_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = USBSPH0_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = WKPU0_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = eMIOS0_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = eMIOS1_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = eMIOS2_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
    {
        .clockName                      = ENET1_CLK,
        .mc_me_RunPeriphConfig          = MC_ME_PERIPH_CONFIG_0,
        .mc_me_LowPowerPeriphConfig     = MC_ME_PERIPH_CONFIG_0,
    },
};
/* *************************************************************************
 * Configuration structure for Clock Configuration 0
 * ************************************************************************* */
/*! @brief User Configuration structure clock_managerCfg_0 */
clock_manager_user_config_t clockMan1_InitConfig0 = {
    /*! @brief Configuration of MC_ME */
    .mcmeConfig =
    {
        .reset =
        {
            .clocksEnabled =
            {
                .sirc          = false,
                .firc          = true,
                .sxosc         = false,
                .fxosc         = false,
                .pll           = false,
            },
            .sysclk            = CGM_SYSTEM_CLOCK_SRC_PLL_PHI0,
        },
        .safe =
        {
            .clocksEnabled =
            {
                .sirc          = false,
                .firc          = true,
                .sxosc         = false,
                .fxosc         = false,
                .pll           = false,
            },
            .sysclk            = CGM_SYSTEM_CLOCK_SRC_PLL_PHI0,
        },
        .drun =
        {
            .clocksEnabled =
            {
                .sirc          = true,
                .firc          = true,
                .sxosc         = true,
                .fxosc         = true,
                .pll           = true,
            },
            .sysclk            = CGM_SYSTEM_CLOCK_SRC_PLL_PHI0,
        },
        .run0 =
        {
            .clocksEnabled =
            {
                .sirc          = false,
                .firc          = true,
                .sxosc         = false,
                .fxosc         = false,
                .pll           = false,
            },
            .sysclk            = CGM_SYSTEM_CLOCK_SRC_PLL_PHI0,
        },
        .run1 =
        {
            .clocksEnabled =
            {
                .sirc          = false,
                .firc          = true,
                .sxosc         = false,
                .fxosc         = false,
                .pll           = false,
            },
            .sysclk            = CGM_SYSTEM_CLOCK_SRC_PLL_PHI0,
        },
        .run2 =
        {
            .clocksEnabled =
            {
                .sirc          = false,
                .firc          = true,
                .sxosc         = false,
                .fxosc         = false,
                .pll           = false,
            },
            .sysclk            = CGM_SYSTEM_CLOCK_SRC_PLL_PHI0,
        },
        .run3 =
        {
            .clocksEnabled =
            {
                .sirc          = false,
                .firc          = true,
                .sxosc         = false,
                .fxosc         = false,
                .pll           = false,
            },
            .sysclk            = CGM_SYSTEM_CLOCK_SRC_PLL_PHI0,
        },
        .stop =
        {
            .clocksEnabled =
            {
                .sirc          = false,
                .firc          = true,
                .sxosc         = false,
                .fxosc         = false,
                .pll           = false,
            },
            .sysclk            = CGM_SYSTEM_CLOCK_SRC_PLL_PHI0,
        },
        .standby =
        {
            .clocksEnabled =
            {
                .sirc          = false,
                .firc          = true,
                .sxosc         = false,
                .fxosc         = false,
                .pll           = false,
            },
            .sysclk            = CGM_SYSTEM_CLOCK_SRC_PLL_PHI0,
        },
        .periphRunConfig[MC_ME_PERIPH_CONFIG_0] =
        {
            .safe               = true,
            .drun               = true,
            .run0               = true,
            .run1               = true,
            .run2               = true,
            .run3               = true,
        },
        .periphRunConfig[MC_ME_PERIPH_CONFIG_1] =
        {
            .safe               = false,
            .drun               = false,
            .run0               = false,
            .run1               = false,
            .run2               = false,
            .run3               = false,
        },
        .periphRunConfig[MC_ME_PERIPH_CONFIG_2] =
        {
            .safe               = false,
            .drun               = false,
            .run0               = false,
            .run1               = false,
            .run2               = false,
            .run3               = false,
        },
        .periphRunConfig[MC_ME_PERIPH_CONFIG_3] =
        {
            .safe               = false,
            .drun               = false,
            .run0               = false,
            .run1               = false,
            .run2               = false,
            .run3               = false,
        },
        .periphRunConfig[MC_ME_PERIPH_CONFIG_4] =
        {
            .safe               = false,
            .drun               = false,
            .run0               = false,
            .run1               = false,
            .run2               = false,
            .run3               = false,
        },
        .periphRunConfig[MC_ME_PERIPH_CONFIG_5] =
        {
            .safe               = false,
            .drun               = false,
            .run0               = false,
            .run1               = false,
            .run2               = false,
            .run3               = false,
        },
        .periphRunConfig[MC_ME_PERIPH_CONFIG_6] =
        {
            .safe               = false,
            .drun               = false,
            .run0               = false,
            .run1               = false,
            .run2               = false,
            .run3               = false,
        },
        .periphRunConfig[MC_ME_PERIPH_CONFIG_7] =
        {
            .safe               = false,
            .drun               = false,
            .run0               = false,
            .run1               = false,
            .run2               = false,
            .run3               = false,
        },
        .periphLowPowerConfig[MC_ME_PERIPH_CONFIG_0] =
        {
            .standby0               = true,
            .stop0               = true,
        },
        .periphLowPowerConfig[MC_ME_PERIPH_CONFIG_1] =
        {
            .standby0               = false,
            .stop0               = false,
        },
        .periphLowPowerConfig[MC_ME_PERIPH_CONFIG_2] =
        {
            .standby0               = false,
            .stop0               = false,
        },
        .periphLowPowerConfig[MC_ME_PERIPH_CONFIG_3] =
        {
            .standby0               = false,
            .stop0               = false,
        },
        .periphLowPowerConfig[MC_ME_PERIPH_CONFIG_4] =
        {
            .standby0               = false,
            .stop0               = false,
        },
        .periphLowPowerConfig[MC_ME_PERIPH_CONFIG_5] =
        {
            .standby0               = false,
            .stop0               = false,
        },
        .periphLowPowerConfig[MC_ME_PERIPH_CONFIG_6] =
        {
            .standby0               = false,
            .stop0               = false,
        },
        .periphLowPowerConfig[MC_ME_PERIPH_CONFIG_7] =
        {
            .standby0               = false,
            .stop0               = false,
        },
        .count                    = 68,
        .peripherals              = peripheralClockMcMeConfig0,
    },

    .cgmConfig =
    {
        .clockout0 =
        {
            .enable              = true,
            .source              = CGM_CLOCKOUT0_SRC_FXOSC,
            .divider             = CGM_CLKOUT0_DIV_BY_1,
        },
        .clockout1 =
        {
            .enable              = true,
            .source              = CGM_CLOCKOUT1_SRC_FXOSC_DIVIDED,
            .divider             = 1,
        },
        .sysClkDividers =
        {
            .s160Enable          = true,
            .s160Divider         = CGM_SYSTEM_CLOCK_DIV_BY_1,

            .s80Enable           = true,
            .s80Divider          = CGM_SYSTEM_CLOCK_DIV_BY_2,

            .s40Enable           = true,
            .s40Divider          = CGM_SYSTEM_CLOCK_DIV_BY_4,

            .f40Enable           = true,
            .f40Divider          = CGM_SYSTEM_CLOCK_DIV_BY_4,

            .f80Enable           = true,
            .f80Divider          = CGM_SYSTEM_CLOCK_DIV_BY_2,

            .fs80Enable          = true,
            .fs80Divider         = CGM_SYSTEM_CLOCK_DIV_BY_2,

            .f20Enable           = true,
            .f20Divider          = CGM_SYSTEM_CLOCK_DIV_BY_8,
        },

        .pllSrc = CGM_PLL_SOURCE_FXOSC,

        .periphClocks =
        {
            .spi0Src              = CGM_SPI0_SOURCE_F40,
            .flexcan0Src          = CGM_FLEXCAN_SOURCE_FXOSC,
            .flexcan1Src          = CGM_FLEXCAN_SOURCE_FXOSC,
            .flexcan2Src          = CGM_FLEXCAN_SOURCE_FXOSC,
            .flexcan3Src          = CGM_FLEXCAN_SOURCE_FXOSC,
            .flexcan4Src          = CGM_FLEXCAN_SOURCE_FXOSC,
            .flexcan5Src          = CGM_FLEXCAN_SOURCE_FXOSC,
            .flexcan6Src          = CGM_FLEXCAN_SOURCE_FXOSC,
            .flexcan7Src          = CGM_FLEXCAN_SOURCE_FXOSC,
            .enetSrc              = CGM_ENET_SOURCE_F40,
            .usdhcSrc             = CGM_USDHC_SOURCE_F40,
        },
    },

    .cgmcsConfig =
    {
        .sircConfig =
        {
            .sircDivider = SIRC_CLOCK_DIV_BY_1,
        },
        .fircConfig =
        {
            .fircDivider = FIRC_CLOCK_DIV_BY_1,
        },
        .sxoscConfig =
        {
            .autoLevelControl   = true,
            .startupDelay       = 1,
            .sxoscDivider       = SXOSC_CLOCK_DIV_BY_1,
        },
        .fxoscConfig =
        {
            .startupDelay       = 1,
            .fxoscDivider       = FXOSC_CLOCK_DIV_BY_1,
            .bypassOption       = FXOSC_USE_CRYSTAL,
            .mode               = FXOSC_FULL_SWING_PIERCE_MODE,
        },
        .plldigConfig =
        {
            .reference                    = CGM_PLL_REFERENCE_FXOSC,
            .predivider                   = PLLDIG_CLOCK_PREDIV_BY_2,
            .denominatorFracLoopDiv       = 9999,
            .numeratorFracLoopDiv         = 0,
            .mulFactorDiv                 = 32,
            .phi0Divider                  = PLLDIG_PHI_DIV_BY_4,
            .phi1Divider                  = PLLDIG_PHI_DIV_BY_4,
        },
    },
};

/*! @brief Array of pointers to User configuration structures */
clock_manager_user_config_t const * g_clockManConfigsArr[] = {
    &clockMan1_InitConfig0
};
/*! @brief Array of pointers to User defined Callbacks configuration structures */
clock_manager_callback_user_config_t * g_clockManCallbacksArr[] = {(void*)0};
/* END clockMan1. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the NXP C55 series of microcontrollers.
**
** ###################################################################
*/
